trigger:
- master

pool:
  vmImage: macos-latest

steps:
- checkout: self
  name: Checkout
- task: UseNode@1
  inputs:
    version: '16.x'
- script: brew install ninja
  displayName: 'Setup Ninja'
- script: sudo xcode-select --switch /Applications/Xcode_13.4.1.app/Contents/Developer
  displayName: 'Select XCode 13.4.1'
- script: npm install
  displayName: 'NPM Install (Playground)'
  workingDirectory: './Apps/Playground'
- script: npm run select --reactNative 0.64
  displayName: 'Select React Native Version 0.64'
  workingDirectory: './Apps/Playground'
- script: npm install
  displayName: 'NPM Install (Binary Package)'
  workingDirectory: './Package'
- script: npx gulp --reactNative 0.64 --releaseVersion 1.6.6.6
  displayName: 'Gulp'
  workingDirectory: './Package'
  env:
    JAVA_HOME: $(JAVA_HOME_11_X64)
    PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
