name: 'Append Release'

on:
  workflow_call:
    inputs:
      release-name:
        required: true
        type: string
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Assembled Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled'
          path: Package/react-native
      - name: Compress Package react-native
        uses: a7ul/tar-action@v1.1.3
        id: compressreact-native
        with:
          command: c
          cwd: Package/react-native/
          files: .
          outPath: react-native.tar.gz

      - name: Download Assembled-BaseKit-iOSAndroid 0.69 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-iOSAndroid0.69'
          path: Package/iOSAndroid0.69
      - name: Compress Package iOSAndroid0.69
        uses: a7ul/tar-action@v1.1.3
        id: compressiosandroid069
        with:
          command: c
          cwd: Package/iOSAndroid0.69/
          files: |
            android
            ios
            react-native-babylon.podspec
          outPath: iOSAndroid0.69.tar.gz

      - name: Download Assembled-BaseKit-iOSAndroid 0.70 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-iOSAndroid0.70'
          path: Package/iOSAndroid0.70
      - name: Compress Package iOSAndroid0.70
        uses: a7ul/tar-action@v1.1.3
        id: compressiosandroid070
        with:
          command: c
          cwd: Package/iOSAndroid0.70/
          files: |
            android
            ios
            react-native-babylon.podspec
          outPath: iOSAndroid0.70.tar.gz

      - name: Download Assembled-BaseKit-iOSAndroid 0.71 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-iOSAndroid0.71'
          path: Package/iOSAndroid0.71
      - name: Compress Package iOSAndroid0.71
        uses: a7ul/tar-action@v1.1.3
        id: compressiosandroid071
        with:
          command: c
          cwd: Package/iOSAndroid0.71/
          files: |
            android
            ios
            react-native-babylon.podspec
          outPath: iOSAndroid0.71.tar.gz

      - name: Download Assembled-BaseKit-Windows 0.69 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-Windows0.69'
          path: Package/Windows0.69
      - name: Compress Package Windows0.69
        uses: a7ul/tar-action@v1.1.3
        id: compresswindows069
        with:
          command: c
          cwd: Package/Windows0.69/
          files: |
            windows
            index.ts
          outPath: Windows0.69.tar.gz

      - name: Download Assembled-BaseKit-Windows 0.70 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-Windows0.70'
          path: Package/Windows0.70
      - name: Compress Package Windows0.70
        uses: a7ul/tar-action@v1.1.3
        id: compresswindows070
        with:
          command: c
          cwd: Package/Windows0.70/
          files: |
            windows
            index.ts
          outPath: Windows0.70.tar.gz

      - name: Download Assembled-BaseKit-Windows 0.71 Folder
        uses: actions/download-artifact@v2
        with:
          name: 'Assembled-BaseKit-Windows0.71'
          path: Package/Windows0.71
      - name: Compress Package Windows0.71
        uses: a7ul/tar-action@v1.1.3
        id: compresswindows071
        with:
          command: c
          cwd: Package/Windows0.71/
          files: |
            windows
            index.ts
          outPath: Windows0.71.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            react-native.tar.gz
            Windows0.69.tar.gz
            Windows0.70.tar.gz
            Windows0.71.tar.gz
            iOSAndroid0.69.tar.gz
            iOSAndroid0.70.tar.gz
            iOSAndroid0.71.tar.gz
          tag_name: ${{ inputs.release-name }}
          name: ${{ inputs.release-name }}
          body: "Release for ${{ inputs.release-name }}"
          draft: false
          prerelease: false
