name: 'build ios-android'

on:
  workflow_call:
    inputs:
      react-native-version:
        required: true
        type: string

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.19.6' # See https://gitlab.kitware.com/cmake/cmake/-/issues/22021
      - name: Setup Ninja
        run: brew install ninja
      - name: NPM Install (Playground)
        run: npm install
        working-directory: ./Apps/Playground
      - name: Select React Native Version ${{ inputs.react-native-version }}
        run: npm run select --reactNative ${{ inputs.react-native-version }}
        working-directory: ./Apps/Playground
      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package
      - name: Gulp
        run: npx gulp --reactNative ${{ inputs.react-native-version }}
        working-directory: ./Package
      - name: Upload Assembled Folder
        uses: actions/upload-artifact@v2
        with:
          name: 'Assembled${{ inputs.react-native-version }}'
          path: Package/Assembled