name: 'build ios-android'

on:
  workflow_call:
    inputs:
      react-native-version:
        required: true
        type: string
      release-version:
        required: true
        type: string
      xcode-version:
        type: string
        default: '16.2'

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: Free space
        uses: ./.github/workflows/macos_freespace
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.26.3'
      - name: Setup Ninja
        run: brew install ninja
      - name: 'Select XCode ${{ inputs.xcode-version }}'
        run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: NPM Install (Playground)
        run: npm install
        working-directory: ./Apps/Playground
      - name: Select React Native Version ${{ inputs.react-native-version }}
        run: npm run select --reactNative ${{ inputs.react-native-version }}
        working-directory: ./Apps/Playground
      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package
      - name: Gulp
        run: npx gulp --reactNative ${{ inputs.react-native-version }} --releaseVersion ${{ inputs.release-version }}
        working-directory: ./Package
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      - name: Upload Assembled iOS Android Folder
        uses: actions/upload-artifact@v4
        with:
          name: 'Assembled-iOSAndroid${{ inputs.react-native-version }}'
          path: Package/Assembled-iOSAndroid
      - name: Upload Assembled iOS Android BaseKit Folder
        uses: actions/upload-artifact@v4
        with:
          name: 'Assembled-BaseKit-iOSAndroid${{ inputs.react-native-version }}'
          path: Package/Assembled-BaseKit-iOSAndroid