name: Test RN/BRN Version
on:
  workflow_dispatch:
    inputs:
      RN_Version:
        description: 'ReactNative Version'
        required: true 
        type: string
        default: '0.69.0'
      BRN_Version:
        description: 'Babylon ReactNative Version'
        required: true 
        type: string
        default: '0-69'

jobs:

  build-windows:
    runs-on: windows-2019
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build Playground Windows x64
      run: |
        npx react-native init Playground --version ${{ github.event.inputs.RN_Version }}
        cd Playground
        npm install @babylonjs/core
        npm install @babylonjs/loaders
        npm install @babylonjs/react-native
        npm install @babylonjs/react-native-iosandroid-${{ github.event.inputs.BRN_Version }}
        npx react-native-windows-init --overwrite
        msbuild.exe /r "./windows/Playground.sln"
        msbuild.exe /p:Configuration="Release" /p:Platform="x64" /m "./windows/Playground.sln"

    - name: Upload UWP x64
      uses: actions/upload-artifact@v2
      with:
        name: 'WindowsUWPx64'
        path: Playground/windows/x64/Release/Playground

  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Build Playground Android
      run: |
        npx react-native init Playground --version ${{ github.event.inputs.RN_Version }}
        cd Playground
        npm install @babylonjs/core
        npm install @babylonjs/loaders
        npm install @babylonjs/react-native
        npm install @babylonjs/react-native-iosandroid-${{ github.event.inputs.BRN_Version }}
        cd android
        ./gradlew app:assembleRelease --stacktrace --info

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: 'AndroidAPK'
        path: Playground/android/app/build/outputs/apk/release/app-release.apk

  package:
    needs: [build-windows, build-android]
    runs-on: macos-latest
    steps:
      - name: Gather 
        run: |
          ls -l -a