name: 'build Typescript'

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package
      - name: NPM Install (Modules)
        run: npm install
        working-directory: ./Modules/@babylonjs/react-native
      - name: NPM Install (Playground)
        run: npm install
        working-directory: ./Apps/Playground

      - name: Gulp
        run: npx gulp buildTS
        working-directory: ./Package
      - name: Upload Assembled Folder
        uses: actions/upload-artifact@v4
        with:
          name: 'Assembled'
          path: Package/Assembled
