name: 'build Typescript'

<<<<<<< HEAD
on: [workflow_call]
=======
on:
  workflow_call:
    inputs:
      Release_Version:
        required: true
        type: string
>>>>>>> 9054098bd2a56512dd6f3c3b44fb3f16aafff97f

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - name: NPM Install (Playground)
        run: npm install
        working-directory: ./Apps/Playground
      - name: Select React Native Version 
        run: npm run select 0.64
        working-directory: ./Apps/Playground
      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package
      - name: Gulp
<<<<<<< HEAD
        run: npx gulp buildTS --releaseVersion ${{ github.event.release.name }}
=======
        run: npx gulp buildTS --releaseVersion ${{ inputs.Release_Version }}
>>>>>>> 9054098bd2a56512dd6f3c3b44fb3f16aafff97f
        working-directory: ./Package
      - name: Upload Assembled Folder
        uses: actions/upload-artifact@v2
        with:
          name: 'Assembled'
          path: Package/Assembled
