name: 'build windows'

on:
  workflow_call:
    inputs:
      WindowsTargetPlatformVersion:
        description: 'Windows Target Platform Version'
        type: string
        default: '10.0.22621.0'
        required: false

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setting up developer environment
        run: |
          Copy-Item -Path "Apps/Playground/package-windows.json" -Destination "Apps/Playground/package.json" -Force
          Copy-Item -Path "Apps/Playground/package-lock-windows.json" -Destination "Apps/Playground/package-lock.json" -Force
          cd Package
          node setup_dev.js

      - name: NPM Generate Windows Project
        run: npx install-windows-test-app
        working-directory: ./Apps/Playground

      - name: Windows build Playground
        run: MSBuild Playground.sln /restore /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=${{ inputs.WindowsTargetPlatformVersion }} /p:WindowsAppSDKVerifyTransitiveDependencies=false /v:minimal
        working-directory: ./Apps/Playground/windows
